name: Deploy FILAB Application

on:
  push:
    branches:
      - main # 监听 main 分支的推送事件

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 连接到服务器并执行部署命令
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器地址
          username: ${{ secrets.SERVER_USER }} # SSH 用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 私钥
          script: |
            cd /www/wwwroot/filab
            git pull origin main
            sudo systemctl restart gunicorn
